export const PAGE_SIZE = [
    {value: '', label: '20'},
    {value: '50', label: '50'},
    {value: '75', label: '75'},
    {value: '100', label: '100'},
];

export const FRAME_TYPE = [
    {value: '', label: 'All'},
    {value:"spell", label: "Spell"},
    {value:"trap", label: "Trap"},
    {value:"monster", label: "Main-deck monster"},
    {value:"extradeck", label: "Extra-deck monster"},
];

export const SPELL_TRAP_RACE = [
    {value: '', label: 'All'},
    {value: "Continuous", label: "Continuous"},
    {value: "Counter", label: "Counter"},
    {value: "Equip", label: "Equip"},
    {value: "Field", label: "Field"},
    {value: "Normal", label: "Normal"},
    {value: "Quick-Play", label: "Quick-Play"},
    {value: "Ritual", label: "Ritual"},
];

export const MONSTER_RACE = [
    {value: '', label: 'All'},
    {value: "Aqua", label: "Aqua"},
    {value: "Beast", label: "Beast"},
    {value: "Beast-Warrior", label: "Beast-Warrior"},
    {value: "Creator God", label: "Creator God"},
    {value: "Cyberse", label: "Cyberse"},
    {value: "Dinosaur", label: "Dinosaur"},
    {value: "Divine-Beast", label: "Divine-Beast"},
    {value: "Dragon", label: "Dragon"},
    {value: "Fairy", label: "Fairy"},
    {value: "Fiend", label: "Fiend"},
    {value: "Fish", label: "Fish"},
    {value: "Illusion", label: "Illusion"},
    {value: "Insect", label: "Insect"},
    {value: "Machine", label: "Machine"},
    {value: "Plant", label: "Plant"},
    {value: "Psychic", label: "Psychic"},
    {value: "Pyro", label: "Pyro"},
    {value: "Reptile", label: "Reptile"},
    {value: "Rock", label: "Rock"},
    {value: "Sea Serpent", label: "Sea Serpent"},
    {value: "Spellcaster", label: "Spellcaster"},
    {value: "Thunder", label: "Thunder"},
    {value: "Warrior", label: "Warrior"},
    {value: "Winged Beast", label: "Winged Beast"},
    {value: "Wyrm", label: "Wyrm"},
    {value: "Yubel", label: "Yubel"},
    {value: "Zombie", label: "Zombie"},
];

export const TYPE = [
    {value:'', label: 'All'},
    {value: "normal", label: "Normal"},
    {value: "effect", label: "Effect"},
    {value: "ritual", label: "Ritual"},
    {value: "fusion", label: "Fusion"},
    {value: "synchro", label: "Synchro"},
    {value: "xyz", label: "Xyz"},
    {value: "toon", label: "Toon"},
    {value: "spirit", label: "Spirit"},
    {value: "union", label: "Union"},
    {value: "gemini", label: "Gemini"},
    {value: "tuner", label: "Tuner"},
    {value: "flip", label: "Flip"},
    {value: "pendulum", label: "Pendulum"},
    {value: "link", label: "Link"},
];

export const ATTRIBUTE = [
    {value:'', label: 'All'},
    {value: "DARK", label: "DARK"},
    {value: "DIVINE", label: "DIVINE"},
    {value: "EARTH", label: "EARTH"},
    {value: "FIRE", label: "FIRE"},
    {value: "LIGHT", label: "LIGHT"},
    {value: "WATER", label: "WATER"},
    {value: "WIND", label: "WIND"},
];

export const ARCHETYPE = [
    {value: '', label: 'All'},
    {value: "\"C\"", label: "\"C\""},
    {value: "-Eyes Dragon", label: "-Eyes Dragon"},
    {value: "25th Anniversary Monsters", label: "25th Anniversary Monsters"},
    {value: "@Ignister", label: "\@Ignister"},
    {value: "A-to-Z", label: "A-to-Z"},
    {value: "A.I.", label: "A.I."},
    {value: "ABC", label: "ABC"},
    {value: "Abyss Actor", label: "Abyss Actor"},
    {value: "Abyss Script", label: "Abyss Script"},
    {value: "Abyss-", label: "Abyss"},
    {value: "Adamancipator", label: "Adamancipator"},
    {value: "Advanced Crystal Beast", label: "Advanced Crystal Beast"},
    {value: "Adventurer", label: "Adventurer"},
    {value: "Adventurer Token", label: "Adventurer Token"},
    {value: "Aesir", label: "Aesir"},
    {value: "Aether", label: "Aether"},
    {value: "Albaz Dragon", label: "Albaz Dragon"},
    {value: "Alien", label: "Alien"},
    {value: "Alligator", label: "Alligator"},
    {value: "Allure Queen", label: "Allure Queen"},
    {value: "Ally of Justice", label: "Ally of Justice"},
    {value: "Altergeist", label: "Altergeist"},
    {value: "Amazement", label: "Amazement"},
    {value: "Amazoness", label: "Amazoness"},
    {value: "Amorphage", label: "Amorphage"},
    {value: "Ancient Fairy Dragon", label: "Ancient Fairy Dragon"},
    {value: "Ancient Gear", label: "Ancient Gear"},
    {value: "Ancient Treasure", label: "Ancient Treasure"},
    {value: "Ancient Warriors", label: "Ancient Warriors"},
    {value: "Anotherverse", label: "Anotherverse"},
    {value: "Anti", label: "Anti"},
    {value: "Apoqliphort", label: "Apoqliphort"},
    {value: "Appliancer", label: "Appliancer"},
    {value: "Aqua Jet", label: "Aqua Jet"},
    {value: "Aquaactress", label: "Aquaactress"},
    {value: "Aquamirror", label: "Aquamirror"},
    {value: "Arcana Force", label: "Arcana Force"},
    {value: "Archfiend", label: "Archfiend"},
    {value: "Argostars", label: "Argostars"},
    {value: "Armed Dragon", label: "Armed Dragon"},
    {value: "Aroma", label: "Aroma"},
    {value: "Artifact", label: "Artifact"},
    {value: "Ashened", label: "Ashened"},
    {value: "Assault Mode", label: "Assault Mode"},
    {value: "Atlantean", label: "Atlantean"},
    {value: "Attraction", label: "Attraction"},
    {value: "Attribute Summoner", label: "Attribute Summoner"},
    {value: "Azamina", label: "Azamina"},
    {value: "B.E.S.", label: "B.E.S."},
    {value: "Bamboo Sword", label: "Bamboo Sword"},
    {value: "Barbaros", label: "Barbaros"},
    {value: "Barian's", label: "Barian's"},
    {value: "Batteryman", label: "Batteryman"},
    {value: "Battleguard", label: "Battleguard"},
    {value: "Battlewasp", label: "Battlewasp"},
    {value: "Battlin' Boxer", label: "Battlin' Boxer"},
    {value: "Battlin' Boxing", label: "Battlin' Boxing"},
    {value: "Beetrooper", label: "Beetrooper"},
    {value: "Black Luster Soldier", label: "Black Luster Soldier"},
    {value: "Blackwing", label: "Blackwing"},
    {value: "Blaze Accelerator", label: "Blaze Accelerator"},
    {value: "Blue Tears", label: "Blue Tears"},
    {value: "Blue-Eyes", label: "Blue-Eyes"},
    {value: "Bonding", label: "Bonding"},
    {value: "Book of", label: "Book of"},
    {value: "Boot-Up", label: "Boot-Up"},
    {value: "Borrel", label: "Borrel"},
    {value: "Bounzer", label: "Bounzer"},
    {value: "Branded", label: "Branded"},
    {value: "Broken World", label: "Broken World"},
    {value: "Bugroth", label: "Bugroth"},
    {value: "Bujin", label: "Bujin"},
    {value: "Burning Abyss", label: "Burning Abyss"},
    {value: "Butterfly", label: "Butterfly"},
    {value: "Butterspy", label: "Butterspy"},
    {value: "Bystial", label: "Bystial"},
    {value: "CXyz", label: "CXyz"},
    {value: "Cataclysmic", label: "Cataclysmic"},
    {value: "Celebration", label: "Celebration"},
    {value: "Celtic Guard", label: "Celtic Guard"},
    {value: "Centur-Ion", label: "Centur-Ion"},
    {value: "Chaos", label: "Chaos"},
    {value: "Chaos Phantom", label: "Chaos Phantom"},
    {value: "Charmer", label: "Charmer"},
    {value: "Chemicritter", label: "Chemicritter"},
    {value: "Chimera", label: "Chimera"},
    {value: "Chronomaly", label: "Chronomaly"},
    {value: "Chrysalis", label: "Chrysalis"},
    {value: "Cipher", label: "Cipher"},
    {value: "Circular", label: "Circular"},
    {value: "Clear", label: "Clear"},
    {value: "Clear Wing", label: "Clear Wing"},
    {value: "Cloudian", label: "Cloudian"},
    {value: "Code Talker", label: "Code Talker"},
    {value: "Codebreaker", label: "Codebreaker"},
    {value: "export Constellar", label: "export Constellar"},
    {value: "Contact", label: "Contact"},
    {value: "Corn", label: "Corn"},
    {value: "Cosmic Synchro Monster", label: "Cosmic Synchro Monster"},
    {value: "Counter Fairy", label: "Counter Fairy"},
    {value: "Crusadia", label: "Crusadia"},
    {value: "Crystal", label: "Crystal"},
    {value: "Crystal Beast", label: "Crystal Beast"},
    {value: "Crystron", label: "Crystron"},
    {value: "Cubic", label: "Cubic"},
    {value: "Cupid", label: "Cupid"},
    {value: "Curse of Dragon", label: "Curse of Dragon"},
    {value: "Cyber", label: "Cyber"},
    {value: "Cyber Angel", label: "Cyber Angel"},
    {value: "Cyber Dragon", label: "Cyber Dragon"},
    {value: "Cyberdark", label: "Cyberdark"},
    {value: "Cynet", label: "Cynet"},
    {value: "D.D.", label: "D.D."},
    {value: "D/D", label: "D/D"},
    {value: "Danger!", label: "Danger!"},
    {value: "Dark Contract", label: "Dark Contract"},
    {value: "Dark Magician", label: "Dark Magician"},
    {value: "Dark Scorpion", label: "Dark Scorpion"},
    {value: "Dark World", label: "Dark World"},
    {value: "Dark counterpart", label: "Dark counterpart"},
    {value: "Darklord", label: "Darklord"},
    {value: "Deep Sea", label: "Deep Sea"},
    {value: "Demise", label: "Demise"},
    {value: "Deskbot", label: "Deskbot"},
    {value: "Despia", label: "Despia"},
    {value: "Destiny HERO", label: "Destiny HERO"},
    {value: "Destruction Sword", label: "Destruction Sword"},
    {value: "Diabell", label: "Diabell"},
    {value: "Diabellstar", label: "Diabellstar"},
    {value: "Dice", label: "Dice"},
    {value: "Digital Bug", label: "Digital Bug"},
    {value: "Dinomist", label: "Dinomist"},
    {value: "Dinomorphia", label: "Dinomorphia"},
    {value: "Dinowrestler", label: "Dinowrestler"},
    {value: "Divine Dragon", label: "Divine Dragon"},
    {value: "Djinn", label: "Djinn"},
    {value: "Dododo", label: "Dododo"},
    {value: "Dogmatika", label: "Dogmatika"},
    {value: "Doll", label: "Doll"},
    {value: "Doll Monster", label: "Doll Monster"},
    {value: "Doodle Beast", label: "Doodle Beast"},
    {value: "Doodlebook", label: "Doodlebook"},
    {value: "Doriado", label: "Doriado"},
    {value: "Draconia", label: "Draconia"},
    {value: "Dracoslayer", label: "Dracoslayer"},
    {value: "Dracoverlord", label: "Dracoverlord"},
    {value: "Dragon Ruler", label: "Dragon Ruler"},
    {value: "Dragonmaid", label: "Dragonmaid"},
    {value: "Dragunity", label: "Dragunity"},
    {value: "Dream Mirror", label: "Dream Mirror"},
    {value: "Drytron", label: "Drytron"},
    {value: "Dual Avatar", label: "Dual Avatar"},
    {value: "Duston", label: "Duston"},
    {value: "Earthbound", label: "Earthbound"},
    {value: "Edge Imp", label: "Edge Imp"},
    {value: "Egyptian God", label: "Egyptian God"},
    {value: "Eldlich", label: "Eldlich"},
    {value: "Eldlixir", label: "Eldlixir"},
    {value: "Elemental HERO", label: "Elemental HERO"},
    {value: "Elemental Lord", label: "Elemental Lord"},
    {value: "Elementsaber", label: "Elementsaber"},
    {value: "Emblema", label: "Emblema"},
    {value: "Empower", label: "Empower"},
    {value: "Empowered Warrior", label: "Empowered Warrior"},
    {value: "Endymion", label: "Endymion"},
    {value: "Evil Eye", label: "Evil Eye"},
    {value: "Evil HERO", label: "Evil HERO"},
    {value: "Evil★Twin", label: "Evil★Twin"},
    {value: "Evol", label: "Evol"},
    {value: "Evolsaur", label: "Evolsaur"},
    {value: "Evoltile", label: "Evoltile"},
    {value: "Evolzar", label: "Evolzar"},
    {value: "Exchange of the Spirit", label: "Exchange of the Spirit"},
    {value: "Exodd", label: "Exodd"},
    {value: "Exodia", label: "Exodia"},
    {value: "Exosister", label: "Exosister"},
    {value: "Eyes Restrict", label: "Eyes Restrict"},
    {value: "F.A.", label: "F.A."},
    {value: "Fabled", label: "Fabled"},
    {value: "Fairy", label: "Fairy"},
    {value: "Fairy Tail", label: "Fairy Tail"},
    {value: "Fan-Made Cards", label: "Fan-Made Cards"},
    {value: "Favorite", label: "Favorite"},
    {value: "Felgrand", label: "Felgrand"},
    {value: "Field Searcher", label: "Field Searcher"},
    {value: "Fiendsmith", label: "Fiendsmith"},
    {value: "Fire Fist", label: "Fire Fist"},
    {value: "Fire Formation", label: "Fire Formation"},
    {value: "Fire King", label: "Fire King"},
    {value: "Firewall", label: "Firewall"},
    {value: "Fishborg", label: "Fishborg"},
    {value: "Flame Swordsman", label: "Flame Swordsman"},
    {value: "Flamvell", label: "Flamvell"},
    {value: "Fleur", label: "Fleur"},
    {value: "Floowandereeze", label: "Floowandereeze"},
    {value: "Flower Cardian", label: "Flower Cardian"},
    {value: "Fluffal", label: "Fluffal"},
    {value: "Forbidden", label: "Forbidden"},
    {value: "Fortress Whale", label: "Fortress Whale"},
    {value: "Fortune Fairy", label: "Fortune Fairy"},
    {value: "Fortune Lady", label: "Fortune Lady"},
    {value: "Fossil", label: "Fossil"},
    {value: "Frightfur", label: "Frightfur"},
    {value: "Frog", label: "Frog"},
    {value: "From the Underworld", label: "From the Underworld"},
    {value: "Fur Hire", label: "Fur Hire"},
    {value: "Fusion", label: "Fusion"},
    {value: "G Golem", label: "G Golem"},
    {value: "Gadget", label: "Gadget"},
    {value: "Gagaga", label: "Gagaga"},
    {value: "Gaia The Fierce Knight", label: "Gaia The Fierce Knight"},
    {value: "Gaia Knight", label: "Gaia Knight"},
    {value: "Galaxy", label: "Galaxy"},
    {value: "Galaxy-Eyes", label: "Galaxy-Eyes"},
    {value: "Gandora", label: "Gandora"},
    {value: "Gate Guardian", label: "Gate Guardian"},
    {value: "Geargia", label: "Geargia"},
    {value: "Gem Dragon", label: "Gem Dragon"},
    {value: "Gem-", label: "Gem-"},
    {value: "Generaider", label: "Generaider"},
    {value: "Genex", label: "Genex"},
    {value: "Ghostrick", label: "Ghostrick"},
    {value: "Ghoti", label: "Ghoti"},
    {value: "Gimmick Puppet", label: "Gimmick Puppet"},
    {value: "Gishki", label: "Gishki"},
    {value: "Gizmek", label: "Gizmek"},
    {value: "Glacial Beast", label: "Glacial Beast"},
    {value: "Gladiator", label: "Gladiator"},
    {value: "Gladiator Beast", label: "Gladiator Beast"},
    {value: "Goblin", label: "Goblin"},
    {value: "Gogogo", label: "Gogogo"},
    {value: "Gold Pride", label: "Gold Pride"},
    {value: "Golden Castle of Stromberg", label: "Golden Castle of Stromberg"},
    {value: "Golden Land", label: "Golden Land"},
    {value: "Gorgonic", label: "Gorgonic"},
    {value: "Gouki", label: "Gouki"},
    {value: "GranSolfachord", label: "GranSolfachord"},
    {value: "Gravekeeper's", label: "Gravekeeper's"},
    {value: "Graydle", label: "Graydle"},
    {value: "Greed", label: "Greed"},
    {value: "Grepher", label: "Grepher"},
    {value: "Guardian", label: "Guardian"},
    {value: "Guardragon", label: "Guardragon"},
    {value: "Gunkan", label: "Gunkan"},
    {value: "Gusto", label: "Gusto"},
    {value: "HERO", label: "HERO"},
    {value: "Harpie", label: "Harpie"},
    {value: "Hazy", label: "Hazy"},
    {value: "Heart", label: "Heart"},
    {value: "Herald", label: "Herald"},
    {value: "Heraldic", label: "Heraldic"},
    {value: "Heraldry", label: "Heraldry"},
    {value: "Heroic", label: "Heroic"},
    {value: "Hi-Speedroid", label: "Hi-Speedroid"},
    {value: "Hieratic", label: "Hieratic"},
    {value: "Hole", label: "Hole"},
    {value: "Holy Knight", label: "Holy Knight"},
    {value: "Horus", label: "Horus"},
    {value: "Horus the Black Flame Dragon", label: "Horus the Black Flame Dragon"},
    {value: "Hyperion", label: "Hyperion"},
    {value: "Ice Barrier", label: "Ice Barrier"},
    {value: "Icejade", label: "Icejade"},
    {value: "Igknight", label: "Igknight"},
    {value: "Impcantation", label: "Impcantation"},
    {value: "Indestructible Insect", label: "Indestructible Insect"},
    {value: "Infernity", label: "Infernity"},
    {value: "Infernoble Arms", label: "Infernoble Arms"},
    {value: "Infernoble Knight", label: "Infernoble Knight"},
    {value: "Infernoid", label: "Infernoid"},
    {value: "Infestation", label: "Infestation"},
    {value: "Infinitrack", label: "Infinitrack"},
    {value: "Invoked", label: "Invoked"},
    {value: "Inzektor", label: "Inzektor"},
    {value: "Iron Chain", label: "Iron Chain"},
    {value: "Jar", label: "Jar"},
    {value: "Jester", label: "Jester"},
    {value: "Jinzo", label: "Jinzo"},
    {value: "Junk", label: "Junk"},
    {value: "Jurrac", label: "Jurrac"},
    {value: "Kaiju", label: "Kaiju"},
    {value: "Kairyu-Shin", label: "Kairyu-Shin"},
    {value: "Karakuri", label: "Karakuri"},
    {value: "Kashtira", label: "Kashtira"},
    {value: "Ki-sikil", label: "Ki-sikil"},
    {value: "Knight", label: "Knight"},
    {value: "Knightmare", label: "Knightmare"},
    {value: "Koa'ki Meiru", label: "Koa'ki Meiru"},
    {value: "Koala", label: "Koala"},
    {value: "Konami Arcade Games", label: "Konami Arcade Games"},
    {value: "Kozmo", label: "Kozmo"},
    {value: "Krawler", label: "Krawler"},
    {value: "Kuriboh", label: "Kuriboh"},
    {value: "Labrynth", label: "Labrynth"},
    {value: "Labyrinth Wall", label: "Labyrinth Wall"},
    {value: "Lady of Lament", label: "Lady of Lament"},
    {value: "Laval", label: "Laval"},
    {value: "Legendary Knight", label: "Legendary Knight"},
    {value: "Libromancer", label: "Libromancer"},
    {value: "Light and Darkness Dragon", label: "Light and Darkness Dragon"},
    {value: "Lightsworn", label: "Lightsworn"},
    {value: "Lil-la", label: "Lil-la"},
    {value: "Live☆Twin", label: "Live☆Twin"},
    {value: "Lswarm", label: "Lswarm"},
    {value: "Lunalight", label: "Lunalight"},
    {value: "Lyrilusc", label: "Lyrilusc"},
    {value: "Machina", label: "Machina"},
    {value: "Machine Angel", label: "Machine Angel"},
    {value: "Madolche", label: "Madolche"},
    {value: "Madoor", label: "Madoor"},
    {value: "Magical Musket", label: "Magical Musket"},
    {value: "Magician", label: "Magician"},
    {value: "Magician Girl", label: "Magician Girl"},
    {value: "Magikey", label: "Magikey"},
    {value: "Magistus", label: "Magistus"},
    {value: "Magnet Warrior", label: "Magnet Warrior"},
    {value: "Majespecter", label: "Majespecter"},
    {value: "Majestic", label: "Majestic"},
    {value: "Maju", label: "Maju"},
    {value: "Malefic", label: "Malefic"},
    {value: "Malicevorous", label: "Malicevorous"},
    {value: "Maliss", label: "Maliss"},
    {value: "Man-Eater Bug", label: "Man-Eater Bug"},
    {value: "Mannadium", label: "Mannadium"},
    {value: "Marincess", label: "Marincess"},
    {value: "Martial Art Spirit", label: "Martial Art Spirit"},
    {value: "Mask", label: "Mask"},
    {value: "Masked HERO", label: "Masked HERO"},
    {value: "Materiactor", label: "Materiactor"},
    {value: "Mathmech", label: "Mathmech"},
    {value: "Mayakashi", label: "Mayakashi"},
    {value: "Mecha Phantom Beast", label: "Mecha Phantom Beast"},
    {value: "Megalith", label: "Megalith"},
    {value: "Mekk-Knight", label: "Mekk-Knight"},
    {value: "Meklord", label: "Meklord"},
    {value: "Melffy", label: "Melffy"},
    {value: "Melodious", label: "Melodious"},
    {value: "Memento", label: "Memento"},
    {value: "Mermail", label: "Mermail"},
    {value: "Metalfoes", label: "Metalfoes"},
    {value: "Metalmorph", label: "Metalmorph"},
    {value: "Metaphys", label: "Metaphys"},
    {value: "Mikanko", label: "Mikanko"},
    {value: "Millennium", label: "Millennium"},
    {value: "Mimighoul", label: "Mimighoul"},
    {value: "Mirror Trap", label: "Mirror Trap"},
    {value: "Mist Valley", label: "Mist Valley"},
    {value: "Mitsurugi", label: "Mitsurugi"},
    {value: "Mokey Mokey", label: "Mokey Mokey"},
    {value: "Monarch", label: "Monarch"},
    {value: "Morganite", label: "Morganite"},
    {value: "Morphtronic", label: "Morphtronic"},
    {value: "Motor", label: "Motor"},
    {value: "Mulcharmy", label: "Mulcharmy"},
    {value: "Mystical Beast of the Forest", label: "Mystical Beast of the Forest"},
    {value: "Mythical Beast", label: "Mythical Beast"},
    {value: "Myutant", label: "Myutant"},
    {value: "Naturia", label: "Naturia"},
    {value: "Nekroz", label: "Nekroz"},
    {value: "Nemeses", label: "Nemeses"},
    {value: "Nemleria", label: "Nemleria"},
    {value: "Nemurelia", label: "Nemurelia"},
    {value: "Neo Space", label: "Neo Space"},
    {value: "Neo-Spacian", label: "Neo-Spacian"},
    {value: "Neos", label: "Neos"},
    {value: "Nephthys", label: "Nephthys"},
    {value: "Nimble", label: "Nimble"},
    {value: "Ninja", label: "Ninja"},
    {value: "Ninjitsu Art", label: "Ninjitsu Art"},
    {value: "Noble Arms", label: "Noble Arms"},
    {value: "Noble Knight", label: "Noble Knight"},
    {value: "Nordic", label: "Nordic"},
    {value: "Nouvelles", label: "Nouvelles"},
    {value: "Number", label: "Number"},
    {value: "Numeron", label: "Numeron"},
    {value: "Odd-Eyes", label: "Odd-Eyes"},
    {value: "Ogdoadic", label: "Ogdoadic"},
    {value: "Ojama", label: "Ojama"},
    {value: "Onomat", label: "Onomat"},
    {value: "Orcust", label: "Orcust"},
    {value: "Overlay", label: "Overlay"},
    {value: "P.U.N.K.", label: "P.U.N.K."},
    {value: "PSY-Frame", label: "PSY-Frame"},
    {value: "Paladins of Dragons", label: "Paladins of Dragons"},
    {value: "Paleozoic", label: "Paleozoic"},
    {value: "PaniK's monsters", label: "PaniK's monsters"},
    {value: "Parasite", label: "Parasite"},
    {value: "Parshath", label: "Parshath"},
    {value: "Patissciel", label: "Patissciel"},
    {value: "Pendulum", label: "Pendulum"},
    {value: "Pendulum Dragon", label: "Pendulum Dragon"},
    {value: "Penguin", label: "Penguin"},
    {value: "Performage", label: "Performage"},
    {value: "Performapal", label: "Performapal"},
    {value: "Phantasm", label: "Phantasm"},
    {value: "Phantasm Spiral", label: "Phantasm Spiral"},
    {value: "Phantom Beast", label: "Phantom Beast"},
    {value: "Phantom Knights", label: "Phantom Knights"},
    {value: "Photon", label: "Photon"},
    {value: "Plunder Patroll", label: "Plunder Patroll"},
    {value: "Polymerization", label: "Polymerization"},
    {value: "Possessed", label: "Possessed"},
    {value: "Potan", label: "Potan"},
    {value: "Power Tool", label: "Power Tool"},
    {value: "Prank-Kids", label: "Prank-Kids"},
    {value: "Predap", label: "Predap"},
    {value: "Predaplant", label: "Predaplant"},
    {value: "Prediction Princess", label: "Prediction Princess"},
    {value: "Priestess", label: "Priestess"},
    {value: "Primite", label: "Primite"},
    {value: "Prophecy", label: "Prophecy"},
    {value: "Puppet", label: "Puppet"},
    {value: "Purrely", label: "Purrely"},
    {value: "Qli", label: "Qli"},
    {value: "Ragnaraika", label: "Ragnaraika"},
    {value: "Raidraptor", label: "Raidraptor"},
    {value: "Rainbow Bridge", label: "Rainbow Bridge"},
    {value: "Raizeol", label: "Raizeol"},
    {value: "Rank-Up-Magic", label: "Rank-Up-Magic"},
    {value: "Recipe", label: "Recipe"},
    {value: "Recolored counterpart", label: "Recolored counterpart"},
    {value: "Red-Eyes", label: "Red-Eyes"},
    {value: "Regenesis", label: "Regenesis"},
    {value: "Relinquished", label: "Relinquished"},
    {value: "Reptilianne", label: "Reptilianne"},
    {value: "Rescue Squad", label: "Rescue Squad"},
    {value: "Rescue-ACE", label: "Rescue-ACE"},
    {value: "Resonator", label: "Resonator"},
    {value: "Rikka", label: "Rikka"},
    {value: "Risebell", label: "Risebell"},
    {value: "Ritual Beast", label: "Ritual Beast"},
    {value: "Roid", label: "Roid"},
    {value: "Rokket", label: "Rokket"},
    {value: "Roland", label: "Roland"},
    {value: "Rose", label: "Rose"},
    {value: "Rose Dragon", label: "Rose Dragon"},
    {value: "Runick", label: "Runick"},
    {value: "Ryu-Ge", label: "Ryu-Ge"},
    {value: "Ryzeal", label: "Ryzeal"},
    {value: "S-Force", label: "S-Force"},
    {value: "SPYRAL", label: "SPYRAL"},
    {value: "Saber", label: "Saber"},
    {value: "Sacred Beast", label: "Sacred Beast"},
    {value: "Salamandra", label: "Salamandra"},
    {value: "Salamangreat", label: "Salamangreat"},
    {value: "Sangen", label: "Sangen"},
    {value: "Scareclaw", label: "Scareclaw"},
    {value: "Schoolwork", label: "Schoolwork"},
    {value: "Scrap", label: "Scrap"},
    {value: "Scrap-Iron", label: "Scrap-Iron"},
    {value: "Sea Stealth", label: "Sea Stealth"},
    {value: "Secret Six Samurai", label: "Secret Six Samurai"},
    {value: "Seventh", label: "Seventh"},
    {value: "Shaddoll", label: "Shaddoll"},
    {value: "Shark", label: "Shark"},
    {value: "Shining Sarcophagus", label: "Shining Sarcophagus"},
    {value: "Shinobird", label: "Shinobird"},
    {value: "Shiranui", label: "Shiranui"},
    {value: "Signature move", label: "Signature move"},
    {value: "Silent Magician", label: "Silent Magician"},
    {value: "Silent Swordsman", label: "Silent Swordsman"},
    {value: "Simorgh", label: "Simorgh"},
    {value: "Sinful Spoils", label: "Sinful Spoils"},
    {value: "Six Samurai", label: "Six Samurai"},
    {value: "Six Strike", label: "Six Strike"},
    {value: "Skilled Magician", label: "Skilled Magician"},
    {value: "Skull Servant", label: "Skull Servant"},
    {value: "Sky Scourge", label: "Sky Scourge"},
    {value: "Sky Striker", label: "Sky Striker"},
    {value: "Skyblaster", label: "Skyblaster"},
    {value: "Slime", label: "Slime"},
    {value: "Snake-Eye", label: "Snake-Eye"},
    {value: "Solemn", label: "Solemn"},
    {value: "Solfachord", label: "Solfachord"},
    {value: "Speedroid", label: "Speedroid"},
    {value: "Spellbook", label: "Spellbook"},
    {value: "Sphinx", label: "Sphinx"},
    {value: "Spider", label: "Spider"},
    {value: "Spirit Message", label: "Spirit Message"},
    {value: "Spiritual Art", label: "Spiritual Art"},
    {value: "Spright", label: "Spright"},
    {value: "Springans", label: "Springans"},
    {value: "Star", label: "Star"},
    {value: "Star Seraph", label: "Star Seraph"},
    {value: "Stardust", label: "Stardust"},
    {value: "Starliege", label: "Starliege"},
    {value: "Starry Knight", label: "Starry Knight"},
    {value: "Stealth Kragen", label: "Stealth Kragen"},
    {value: "Steelswarm", label: "Steelswarm"},
    {value: "Stellarknight", label: "Stellarknight"},
    {value: "Subterror", label: "Subterror"},
    {value: "Sunavalon", label: "Sunavalon"},
    {value: "Sunseed", label: "Sunseed"},
    {value: "Sunvine", label: "Sunvine"},
    {value: "Super Defense Robot", label: "Super Defense Robot"},
    {value: "Super Quant", label: "Super Quant"},
    {value: "Superheavy", label: "Superheavy"},
    {value: "Superheavy Samurai", label: "Superheavy Samurai"},
    {value: "Supreme King", label: "Supreme King"},
    {value: "Swarm of", label: "Swarm of"},
    {value: "Swordsoul", label: "Swordsoul"},
    {value: "Sylvan", label: "Sylvan"},
    {value: "Symphonic Warrior", label: "Symphonic Warrior"},
    {value: "Synchro", label: "Synchro"},
    {value: "Synchron", label: "Synchron"},
    {value: "T.G.", label: "T.G."},
    {value: "Tachyon", label: "Tachyon"},
    {value: "Tearlaments", label: "Tearlaments"},
    {value: "Tellarknight", label: "Tellarknight"},
    {value: "Tenpai Dragon", label: "Tenpai Dragon"},
    {value: "Tenyi", label: "Tenyi"},
    {value: "Test", label: "Test"},
    {value: "The Agent", label: "The Agent"},
    {value: "The Sanctuary in the Sky", label: "The Sanctuary in the Sky"},
    {value: "The Weather", label: "The Weather"},
    {value: "Therion", label: "Therion"},
    {value: "Thunder Dragon", label: "Thunder Dragon"},
    {value: "Time Thief", label: "Time Thief"},
    {value: "Timelord", label: "Timelord"},
    {value: "Tindangle", label: "Tindangle"},
    {value: "Tistina", label: "Tistina"},
    {value: "Toon", label: "Toon"},
    {value: "Toy", label: "Toy"},
    {value: "Train", label: "Train"},
    {value: "Transcendosaurus", label: "Transcendosaurus"},
    {value: "Trap Hole", label: "Trap Hole"},
    {value: "Trap Monster", label: "Trap Monster"},
    {value: "Traptrix", label: "Traptrix"},
    {value: "Tri-Brigade", label: "Tri-Brigade"},
    {value: "Triamid", label: "Triamid"},
    {value: "Trickstar", label: "Trickstar"},
    {value: "True Draco", label: "True Draco"},
    {value: "U.A.", label: "U.A."},
    {value: "Umbral Horror", label: "Umbral Horror"},
    {value: "Umi", label: "Umi"},
    {value: "Unchained", label: "Unchained"},
    {value: "Underworld", label: "Underworld"},
    {value: "Uniform Nomenclature", label: "Uniform Nomenclature"},
    {value: "Ursarctic", label: "Ursarctic"},
    {value: "Utopia", label: "Utopia"},
    {value: "Utopic", label: "Utopic"},
    {value: "Vaalmonica", label: "Vaalmonica"},
    {value: "Valkyrie", label: "Valkyrie"},
    {value: "Vampire", label: "Vampire"},
    {value: "Vanquish Soul", label: "Vanquish Soul"},
    {value: "Vassal", label: "Vassal"},
    {value: "Vaylantz", label: "Vaylantz"},
    {value: "Veda", label: "Veda"},
    {value: "Vendread", label: "Vendread"},
    {value: "Venom", label: "Venom"},
    {value: "Vernusylph", label: "Vernusylph"},
    {value: "Virtual World", label: "Virtual World"},
    {value: "Visas", label: "Visas"},
    {value: "Vision HERO", label: "Vision HERO"},
    {value: "Voiceless Voice", label: "Voiceless Voice"},
    {value: "Void", label: "Void"},
    {value: "Volcanic", label: "Volcanic"},
    {value: "Vylon", label: "Vylon"},
    {value: "War Rock", label: "War Rock"},
    {value: "Watt", label: "Watt"},
    {value: "Wedju", label: "Wedju"},
    {value: "White", label: "White"},
    {value: "White Forest", label: "White Forest"},
    {value: "Wicked God", label: "Wicked God"},
    {value: "Wight", label: "Wight"},
    {value: "Wind-Up", label: "Wind-Up"},
    {value: "Windwitch", label: "Windwitch"},
    {value: "Witchcrafter", label: "Witchcrafter"},
    {value: "World Chalice", label: "World Chalice"},
    {value: "World Legacy", label: "World Legacy"},
    {value: "Worm", label: "Worm"},
    {value: "X-Saber", label: "X-Saber"},
    {value: "Xyz", label: "Xyz"},
    {value: "Yang Zing", label: "Yang Zing"},
    {value: "Yosenju", label: "Yosenju"},
    {value: "Yubel", label: "Yubel"},
    {value: "Zefra", label: "Zefra"},
    {value: "Zera", label: "Zera"},
    {value: "Zexal", label: "Zexal"},
    {value: "Zombie counterpart", label: "Zombie counterpart"},
    {value: "Zoodiac", label: "Zoodiac"},
    {value: "hunder", label: "hunder"},
    {value: "roid", label: "roid"},
    {value: "tellarknight", label: "tellarknight"},
    {value: "with Eyes of Blue", label: "with Eyes of Blue"},
];